//
// Created by  on 22.08.2019.
//

#ifndef INCLUDE_GAME_COMPONENTS_PLAYERCOMPONENTS_KEYCOMPONENT_H_
#define INCLUDE_GAME_COMPONENTS_PLAYERCOMPONENTS_KEYCOMPONENT_H_

#include "ecs/IComponent.h"

class KeyComponent : public IComponent {};

#endif  // INCLUDE_GAME_COMPONENTS_PLAYERCOMPONENTS_KEYCOMPONENT_H_
