//
// Created by  on 03.08.2019.
//

#ifndef INCLUDE_GAME_COMPONENTS_PLAYERCOMPONENTS_PLAYERCOMPONENT_H_
#define INCLUDE_GAME_COMPONENTS_PLAYERCOMPONENTS_PLAYERCOMPONENT_H_

#include "ecs/IComponent.h"

class PlayerComponent : public IComponent {};

#endif  // INCLUDE_GAME_COMPONENTS_PLAYERCOMPONENTS_PLAYERCOMPONENT_H_
