//
// Created by AsTeFu on 24.07.2019.
//

#ifndef INCLUDE_GAME_ROOMMANAGER_BUILDERS_ROOMWRITER_H_
#define INCLUDE_GAME_ROOMMANAGER_BUILDERS_ROOMWRITER_H_

class RoomWriter {};

#endif  // INCLUDE_GAME_ROOMMANAGER_BUILDERS_ROOMWRITER_H_
